apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
spec:
  selector:
    app: weatherapp         #Must match the pod label
  ports:
    - port: 3000            #This is the service port
      targetPort: 3000      #This is the container port
  type: LoadBalancer        #type of service